import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Web3 Kit</title>
        <meta name="description" content="Generated by create-w3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#add7ff] to-[#fffac2]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Create <span className="text-text-[#d0679d]">W3</span> App
          </h1>
          <span className="text-center text-black">
            Privy & Tailwind with Pages router
          </span>
        </div>
      </main>
    </>
  );
}
