import Head from "next/head";

import styles from "./index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Web3 Kit</title>
        <meta name="description" content="Generated by create-w3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>W3</span> App
          </h1>
          <span className={styles.description}>Privy with Pages router</span>
        </div>
      </main>
    </>
  );
}
