import "@rainbow-me/rainbowkit/styles.css";
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import Providers from "../components/provider/rainbow-provider";

export const metadata: Metadata = {
  title: "Create Web3 Kit",
  description: "Generated by create-w3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
